# Generated by Django 5.1 on 2024-09-13 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(to='facebook.socialuser')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('comment', models.ManyToManyField(related_name='com', to='facebook.comment')),
                ('likers', models.ManyToManyField(related_name='liker', to='facebook.socialuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facebook.socialuser')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ManyToManyField(to='facebook.socialuser'),
        ),
    ]
